/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.Clientes;
import java.awt.Desktop;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import org.apache.poi.hssf.usermodel.HSSFClientAnchor;
import org.apache.poi.hssf.usermodel.HSSFPatriarch;
import org.apache.poi.hssf.usermodel.HSSFPicture;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import org.apache.poi.ss.usermodel.ClientAnchor;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Drawing;
import org.apache.poi.ss.usermodel.Picture;
import org.apache.poi.util.IOUtils;

/**
 *
 * @author Kaze
 */
public class Dialogo_Cliente extends javax.swing.JDialog {
    Boolean EsNuevo=true;
    Boolean habilitar=false;
    
    public void habilitarDeshabilitar(Boolean b){
        txtNombre.setEditable(b);
        txtApellidos.setEditable(b);
        txtDireccion.setEditable(b);
        txtCI.setEditable(b);
        txtNIT.setEditable(b);
        txtTelfCasa.setEditable(b);
        txtTelfEmp.setEditable(b);
        txtCelular.setEditable(b);
        txtCelular2.setEditable(b);
        txtDireccion.setEditable(b);
        chkLuz.setEnabled(b);
        chkAgua.setEnabled(b);
        txtEmpresa.setEditable(b);
        txtEmail.setEditable(b);
        txtProfesion.setEditable(b);
        chkNoGrato.setEnabled(b);
        cmdGuardar.setEnabled(b);
        mnuGuardar.setEnabled(b);
        cmdFoto.setVisible(b);
    }
    public void cargarDatos(){
        if (Clases.General.CargarDatos==true){
            txtNombre.setText(Clases.Clientes.CNombre);
            txtApellidos.setText(Clases.Clientes.CApellidos);
            txtCI.setText(Clases.Clientes.CCI);
            txtNIT.setText(Clases.Clientes.CNIT);
            txtTelfCasa.setText(Clases.Clientes.CTelfCasa);
            txtTelfEmp.setText(Clases.Clientes.CTelfEmp);
            txtCelular.setText(Clases.Clientes.CCel);
            txtCelular2.setText(Clases.Clientes.CCel2);
            txtDireccion.setText(Clases.Clientes.CDireccion);
            if (Clases.Clientes.CLuz==true)chkLuz.setSelected(true);
            else chkLuz.setSelected(false);
            if (Clases.Clientes.CAgua==true)chkAgua.setSelected(true);
            else chkAgua.setSelected(false);
            txtEmpresa.setText(Clases.Clientes.CEmpresa);
            txtEmail.setText(Clases.Clientes.CEmail);
            txtProfesion.setText(Clases.Clientes.CProfesion);
            if (Clases.Clientes.CNoGrato==true)chkNoGrato.setSelected(true);
            else chkNoGrato.setSelected(false);
            cmdEliminar.setEnabled(true);
            mnuEliminar.setEnabled(true);
            mnuModificar.setEnabled(true);
            habilitar=false;
            //Creamos un File con la ruta de la foto que necesitamos
            File archivo = new File("img/"+Clases.Clientes.ID_Cliente+".jpg");
            if (archivo.exists()){//si el archivo con esa ruta existe cargamos la foto
                ImageIcon icon = new ImageIcon("img/"+Clases.Clientes.ID_Cliente+".jpg");
                //redimensionamos la foto
                Image mini = icon.getImage().getScaledInstance(100, 100, Image.SCALE_AREA_AVERAGING);
                Foto.setIcon(new ImageIcon(mini));
            }else{//Sino, cargamos la imagen por defecto.
                Foto.setIcon(new ImageIcon(getClass().getResource("/Recursos/none.jpg")));
            }
        }
        else{
            cmdEliminar.setEnabled(false);
            mnuEliminar.setEnabled(false);
            mnuModificar.setEnabled(false);
            habilitar=true;
            Clases.Clientes.ID_Cliente=0;
            Foto.setIcon(new ImageIcon(getClass().getResource("/Recursos/none.jpg")));
        }
    }
    /**
     * Creates new form Dialogo_Cliente
     */
    public Dialogo_Cliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        cargarDatos();
        habilitarDeshabilitar(habilitar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCI = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTelfCasa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelfEmp = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCelular2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        chkLuz = new javax.swing.JCheckBox();
        chkAgua = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        chkNoGrato = new javax.swing.JCheckBox();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtNIT = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        txtProfesion = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Foto = new javax.swing.JLabel();
        cmdFoto = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnuGuardar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mnuModificar = new javax.swing.JMenuItem();
        mnuEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setResizable(false);

        jLabel1.setText("Nombre:");

        jLabel2.setText("Apellidos:");

        jLabel3.setText("C.I.:");

        jLabel4.setText("Telf. Casa:");

        jLabel5.setText("Telf. Empresa:");

        jLabel6.setText("Celular:");

        jLabel7.setText("Celular 2:");

        jLabel8.setText("Dirección:");

        chkLuz.setText("Factura de Luz");

        chkAgua.setText("Factura de Agua");

        jLabel11.setText("Empresa del Cliente:");

        chkNoGrato.setText("Cliente No Grato");
        chkNoGrato.setNextFocusableComponent(cmdGuardar);

        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });

        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });

        jLabel9.setText("NIT:");

        jLabel10.setText("E-Mail:");

        jLabel12.setText("Profesión:");

        Foto.setToolTipText("Abrir imagen");
        Foto.setAlignmentY(0.0F);
        Foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        Foto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FotoMouseClicked(evt);
            }
        });

        cmdFoto.setText("Agregar Foto");
        cmdFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdFotoActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        mnuGuardar.setText("Guardar");
        mnuGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGuardarActionPerformed(evt);
            }
        });
        jMenu1.add(mnuGuardar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        mnuModificar.setText("Modificar Este Cliente");
        mnuModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuModificarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuModificar);

        mnuEliminar.setText("Eliminar Este Cliente");
        mnuEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(mnuEliminar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTelfCasa)
                                            .addComponent(txtTelfEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCelular2))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtEmpresa))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtEmail)
                                            .addGap(104, 104, 104))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmdGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4)
                                .addComponent(cmdEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(chkLuz)
                                    .addGap(18, 18, 18)
                                    .addComponent(chkAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(chkNoGrato, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Foto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmdFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtApellidos))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtCI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(txtNIT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmdFoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtTelfCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCelular2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtTelfEmp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkLuz)
                    .addComponent(chkAgua)
                    .addComponent(chkNoGrato))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdEliminar)
                    .addComponent(cmdGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Foto.getAccessibleContext().setAccessibleName("foto");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuModificarActionPerformed
        if (mnuModificar.isEnabled()==true){
            habilitarDeshabilitar(true);
            EsNuevo=false;
        }
    }//GEN-LAST:event_mnuModificarActionPerformed

    private void mnuEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar este cliente?")==0){
            try {
                Clases.Clientes.eliminarCliente();
                this.setVisible(false);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Dialogo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Dialogo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnuEliminarActionPerformed

    private void mnuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGuardarActionPerformed
            Clases.Clientes.CNombre=txtNombre.getText();
            Clases.Clientes.CApellidos=txtApellidos.getText();
            Clases.Clientes.CCI=txtCI.getText();
            Clases.Clientes.CNIT=txtNIT.getText();
            Clases.Clientes.CTelfCasa=txtTelfCasa.getText();
            Clases.Clientes.CTelfEmp=txtTelfEmp.getText();
            Clases.Clientes.CCel=txtCelular.getText();
            Clases.Clientes.CCel2=txtCelular2.getText();
            Clases.Clientes.CDireccion=txtDireccion.getText();
            if (chkLuz.isSelected()) Clases.Clientes.CLuz=true;else Clases.Clientes.CLuz=false;
            if (chkAgua.isSelected()) Clases.Clientes.CAgua=true;else Clases.Clientes.CAgua=false;
            Clases.Clientes.CEmpresa=txtEmpresa.getText();
            Clases.Clientes.CEmail=txtEmail.getText();
            Clases.Clientes.CProfesion=txtProfesion.getText();
            if (chkNoGrato.isSelected()) Clases.Clientes.CNoGrato=true;else Clases.Clientes.CNoGrato=false;
            try {
                if (EsNuevo==true){
                    Clases.Clientes.guardarNuevoCliente();
                }
                else{
                    if (JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer modificar este cliente?")==0){
                        Clases.Clientes.modificarCliente();
                    }
                }
                this.setVisible(false);
            } 
            catch (IOException ex) {         
            }
    }//GEN-LAST:event_mnuGuardarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "¿Seguro que desea eliminar este cliente?")==0){
            try {
                Clases.Clientes.eliminarCliente();
                this.setVisible(false);
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Dialogo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Dialogo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (cmdGuardar.isEnabled()==true){
            Clases.Clientes.CNombre=txtNombre.getText();
            Clases.Clientes.CApellidos=txtApellidos.getText();
            Clases.Clientes.CCI=txtCI.getText();
            Clases.Clientes.CNIT=txtNIT.getText();
            Clases.Clientes.CTelfCasa=txtTelfCasa.getText();
            Clases.Clientes.CTelfEmp=txtTelfEmp.getText();
            Clases.Clientes.CCel=txtCelular.getText();
            Clases.Clientes.CCel2=txtCelular2.getText();
            Clases.Clientes.CDireccion=txtDireccion.getText();
            if (chkLuz.isSelected()) Clases.Clientes.CLuz=true;else Clases.Clientes.CLuz=false;
            if (chkAgua.isSelected()) Clases.Clientes.CAgua=true;else Clases.Clientes.CAgua=false;
            Clases.Clientes.CEmpresa=txtEmpresa.getText();
            Clases.Clientes.CEmail=txtEmail.getText();
            Clases.Clientes.CProfesion=txtProfesion.getText();
            if (chkNoGrato.isSelected()) Clases.Clientes.CNoGrato=true;else Clases.Clientes.CNoGrato=false;
            try {
                if (EsNuevo==true){
                    Clases.Clientes.guardarNuevoCliente();
                }
                else{
                    if (JOptionPane.showConfirmDialog(rootPane, "¿Está seguro de querer modificar este cliente?")==0){
                        Clases.Clientes.modificarCliente();
                    }
                }
                this.setVisible(false);
            } 
            catch (IOException ex) {         
            }
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdFotoActionPerformed
        JFileChooser j = new JFileChooser();
        j.showOpenDialog(null); //Abrimos un dialogo de selección de archivo
        File archivo = j.getSelectedFile();
        Clases.General.rutaImagen = archivo.getAbsolutePath(); //cargamos en 'ruta' la ruta de la imagen.
        ImageIcon icon = new ImageIcon(Clases.General.rutaImagen); 
        //redimensionamos la foto
        Image mini = icon.getImage().getScaledInstance(100, 100, Image.SCALE_AREA_AVERAGING);
        Foto.setIcon(new ImageIcon(mini));
    }//GEN-LAST:event_cmdFotoActionPerformed

    private void FotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FotoMouseClicked
        Desktop desktop = Desktop.getDesktop(); //Instanciamos la clase Desktop
        String ruta="img/"+Clases.Clientes.ID_Cliente+".jpg"; //Le damos la ruta del archivo.
        File archivo = new File(ruta); //Instanciamos la clase File con esa ruta.+
        if (archivo.exists()){
            try {
                desktop.open(archivo); //el método open de la clase Desktop llama al programa prederminado que abre ese archivo.
            } catch (IOException ex) {
                Logger.getLogger(Dialogo_Cliente.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_FotoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialogo_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialogo_Cliente dialog = new Dialogo_Cliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Foto;
    private javax.swing.JCheckBox chkAgua;
    private javax.swing.JCheckBox chkLuz;
    private javax.swing.JCheckBox chkNoGrato;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JToggleButton cmdFoto;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JMenuItem mnuEliminar;
    private javax.swing.JMenuItem mnuGuardar;
    private javax.swing.JMenuItem mnuModificar;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCI;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtCelular2;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtNIT;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtProfesion;
    private javax.swing.JTextField txtTelfCasa;
    private javax.swing.JTextField txtTelfEmp;
    // End of variables declaration//GEN-END:variables
}
