/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.poifs.filesystem.POIFSFileSystem;
import Clases.General;
/**
 *
 * @author Kaze
 */
public class Panel_Ingresos extends javax.swing.JPanel {
    public void cargartablaIngresos() throws IOException{
        General.ModeloTablaIngresos.setRowCount(0);
        General.ModeloTablaIngresos.setColumnCount(0);
        tablaIngresos.setModel(Clases.General.ModeloTablaIngresos);
        General.ModeloTablaIngresos.addColumn("ID");
        General.ModeloTablaIngresos.addColumn("Cliente");
        General.ModeloTablaIngresos.addColumn("Fecha Entrega");
        General.ModeloTablaIngresos.addColumn("Cobrado por");
        General.ModeloTablaIngresos.addColumn("Monto");
        tablaIngresos.setModel(Clases.General.ModeloTablaIngresos); //Asignamos el Modelo a la tablaIngresos.
    }
    public void calcularTodos() throws FileNotFoundException, IOException{
        General.ModeloTablaIngresos.setRowCount(0);
        tablaIngresos.setModel(Clases.General.ModeloTablaIngresos);
        POIFSFileSystem fs = new POIFSFileSystem(new FileInputStream("SokolmetDB"));
        HSSFWorkbook libro = new HSSFWorkbook(fs);
        HSSFSheet Clientes = libro.getSheetAt(0);
        HSSFSheet Alquileres = libro.getSheetAt(1);
        int NumClientes = Clientes.getLastRowNum();
        int NumAlquileres = Alquileres.getLastRowNum();
        double total=0.0, superTotal=0.0;
        Object Datos[]=new Object[5]; //Numero de columnas de la tablaIngresos, es un Array de objetos.
        for (int i=1;i<=NumAlquileres;i++){//recorre las filas
            if (Alquileres.getRow(i).getCell(25).getBooleanCellValue()==false){
            Datos[0]=(int)Alquileres.getRow(i).getCell(0).getNumericCellValue();
            //Dejamos la posición 1 para el final pues necesita una pequeña búsqueda.
            Datos[2]=Alquileres.getRow(i).getCell(23);
            Datos[3]=Alquileres.getRow(i).getCell(27);
            total=((double)Alquileres.getRow(i).getCell(6).getNumericCellValue()
                 +(double)Alquileres.getRow(i).getCell(9).getNumericCellValue()
                 +(double)Alquileres.getRow(i).getCell(12).getNumericCellValue()
                 +(double)Alquileres.getRow(i).getCell(15).getNumericCellValue()
                 +(double)Alquileres.getRow(i).getCell(18).getNumericCellValue()
                 +(double)Alquileres.getRow(i).getCell(21).getNumericCellValue())
                 *(int)Alquileres.getRow(i).getCell(26).getNumericCellValue();
            superTotal+=total;
            Datos[4]=General.redondear(total);
            for (int j=1;j<=NumClientes;j++){
                if (Clientes.getRow(j).getCell(0).getNumericCellValue()==Alquileres.getRow(i).getCell(1).getNumericCellValue()){
                    //Buscamos el cliente que tiene el ID del alquiler que estamos mostrando
                    //Cargamos el campo de la lista con el Nombre y los Apellidos
                    Datos[1]=Clientes.getRow(j).getCell(1)+ " " + Clientes.getRow(j).getCell(2);
                }
            }
            General.ModeloTablaIngresos.addRow(Datos); //Añadimos una fila con el Array Datos.
        }
        tablaIngresos.setModel(Clases.General.ModeloTablaIngresos); //Asignamos el Modelo a la tablaIngresos.
        lblTotal.setText(String.valueOf(General.redondear(superTotal)));
        }
    }
    public void calcularSemana(){
        
    }
    public void calcularMes(){
        
    }
    public void calcularAnio(){
        
    }
    /**
     * Creates new form Panel_Ingresos
     */
    public Panel_Ingresos() throws IOException {
        initComponents();
        cargartablaIngresos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cboRango = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaIngresos = new javax.swing.JTable();
        cmdCalcular = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();

        jLabel1.setText("Ingresos obtenidos por alquileres pagados:");

        jLabel3.setText("Mostrar:");

        cboRango.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Esta Semana", "Este Mes", "Este año" }));

        tablaIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaIngresos);

        cmdCalcular.setText("Calcular");
        cmdCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcularActionPerformed(evt);
            }
        });

        jLabel2.setText("Total en Bolivianos: ");

        lblTotal.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboRango, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cboRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cmdCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcularActionPerformed
        try {
            switch (cboRango.getSelectedIndex()){
                case 0: calcularTodos();System.out.println("todos");break;
                case 1: calcularSemana();System.out.println("semana");break;
                case 2: calcularMes();System.out.println("mes");break;
                case 3: calcularAnio();System.out.println("año");break;
            }
        }catch (FileNotFoundException ex) {
            Logger.getLogger(Panel_Ingresos.class.getName()).log(Level.SEVERE, null, ex);
        }catch (IOException ex) {
            Logger.getLogger(Panel_Ingresos.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_cmdCalcularActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable tablaIngresos;
    private javax.swing.JComboBox cboRango;
    private javax.swing.JButton cmdCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotal;
    // End of variables declaration//GEN-END:variables
}
